sudo: required
services:
  - docker

before_install:
  - docker build -t grimro/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true grimro/react-test npm test

after_success:
  - docker build -t grimro/multi-client ./client
  - docker build -t grimro/multi-nginx ./nginx
  - docker build -t grimro/multi-server ./server
  - docker build -t grimro/multi-worker ./worker
  # Log in to docker CLI
  - echo "$DOCKER_PASS" | docker login -u "$DOCKER_ID" --password-stdin
  # Take these images and push them to docker hub
  - docker push grimro/multi-client
  - docker push grimro/multi-nginx
  - docker push grimro/multi-server
  - docker push grimro/multi-worker
